select listings.id, 
listings.brokerage_id, 
reso_reso_properties.listing_id, 
reso_reso_properties.unparsed_address,
reso_reso_properties.unit_number,
reso_reso_properties.list_agent_full_name,
reso_reso_properties.co_list_agent_full_name,
properties.agent_id,
-- Required Fields
listings.sale_or_rental,
listings.building_id,
listings.property_type_code,
features.structure_type,
features.tax_block,
reso_reso_properties.standard_status,
listings.list_date,
expiration,
lease_term_min_months,
listings.concessions_given,
listings.listing_agreement,
listings.cobroke_agreement,
listings.office_id,
listings.buyer_brokerage_compensation_type,
description,
listings.showing_instructions,
published,
features.year_built,
amenities.garage,
features.elevators_total,
features.attendance_type ,
features.stories_total,
features.number_of_units_total,
features.laundry_features,
features.bedrooms,
listings.rooms,
-- Conditional Fields
properties.buyer_agent_id,
properties.buyer_office_id,
listings.lease_type,
features.tax_lot,
listings.contract_date,
listings.sale_date,
listings.sale_price,
listings.cancellation_date,
listings.furnished,
listings.special_listing_conditions,
reso_reso_properties.list_price,
listings.furnished_rent,
available_date,
lease_term_max_months,
listings.max_financing_pct,
listings.maximum_financing_remarks,
reso_reso_properties.number_of_shares,
reso_reso_properties.percent_of_common_elements,
features.capital_reserves_total,
properties.hoa_fee,
features.association_fee_frequency,
real_estate_tax,
features.tax_abatement_expiration_year,
features.tax_abatement_notes,
listings.flip_tax_pct,
listings.flip_tax_amount,
flip_tax_description,
reso_reso_properties.concessions_comments,
listings.owner_pays_plus_concessions_y_n,
listings.owner_pays,
listings.owner_pays_remarks,
commission_type,
commission_amount,
listings.commission_remarks,
listings.bonus,
listings.showing_end_time,
reso_reso_properties.syndicate_to,
features.overall_condition,
reso_reso_properties.sponsor_unit_y_n,
features.lot_size_area,
features.lot_size_units,
features.lot_size_dimensions,
features.building_size_dimensions,
features.building_area_total,
features.building_area_units,
reso_reso_properties.lot_size_square_feet,
features.garage_spaces,
features.pet_policy,
features.pet_policy_remarks,
features.basement_type,
features.heating,
features.cooling,
features.view,
reso_reso_properties.view_y_n,
reso_reso_properties.bonus_y_n,
features.fireplace_features,
features.bathrooms,
features.half_bathrooms,
features.basement_y_n,
features.configuration_type,
features.cooling_y_n,
features.garage_spaces_assigned_y_n,
reso_reso_properties.new_construction_y_n,
reso_reso_properties.new_development_y_n,
features.heating_y_n,
listings.showing_start_time,
features.total_fireplaces,
syndications.rls,
syndications.rls_syndication_portals
from listings
JOIN reso_reso_properties ON reso_reso_properties.listing_id = listings.rebny_id
left join features on features.features_id = listings.id
left join amenities on amenities.amenities_id = listings.id
left join properties on properties.id = listings.building_id
left join syndications on syndications.listing_id = listings.id
where listings.brokerage_id = '4885'
AND listings.hidden is false
AND listings.published is true 
AND reso_reso_properties.standard_status in ('Coming Soon', 'Active', 'Pending')