select list_office_name, count(distinct(list_agent_key)) as agent_count, count(distinct(listing_id)) as listing_count
from reso_reso_properties
where list_office_name in
('Coldwell Banker Commercial',
'RE/MAX Results Plus',
'Eagle Realty Group LLC',
'ORP Properties, Inc.',
'Thesing Real Estate Services',
'RE/MAX Unlimited',
'Koogler-Eyre Realtors',
'Firstar Corporate Real Estate',
'Ohio National Life Ins. Co.',
'The Clay Group',
'House Calls, LLC',
'Cincy Photo Pro',
'HFS.com Real Estate, LLC',
'Madison Savings Bank',
'Real Living Village Realty',
'Sibcy Cline, Inc.',
'ERA REAL Solutions Realty. LLC',
'Coldwell Banker Heritage',
'Integral Real Estate Serv. LLC',
'Private Real Estate Collection',
'Renu Property Mgt Ohio LLC',
'L & W Properties of Ohio LLC',
'Netilie B. Carney',
'HER, REALTORSÃ‚Â®',
'HER, REALTORSÃ‚Â®',
'Vylla Home',
'HomeBackers',
'Heritage Hill Realty',
'One Hundred, Inc., Realtors',
'BH&G Real Estate Big Hill',
'Better Homes And Gardens Real',
'Suburban Federal Savings Bank',
'RE/MAX Victory + Affiliates',
'Oak Hills Savings & Loan',
'Land Sales & Service',
'Coldwell Banker Oyer Inc.',
'Real Living Village Realty',
'First Trust Mortgage Company',
'Sunderman & Hartley Realty',
'HER, REALTORSÃ‚Â®',
'Re/Max Incline Real Estate',
'EveryState Inc.',
'TPH ZeroDown Brokerage TX LLC',
'CRESA Cincinnati Region LLC')
and originating_system_i_d = 'cincymls'
group by 1;